export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_USERNAME_ALREADY_EXISTS: "USER_USERNAME_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  BANK_NAME_ALREADY_EXISTS: "BANK_NAME_ALREADY_EXISTS",
  BANK_NOT_FOUND: "BANK_NOT_FOUND",
  BANK_ACCESS_FORBIDDEN: "BANK_ACCESS_FORBIDDEN",
} as const;